# .tmux.conf


#――――――――――――――――――――――――――――――――
# plugins
#――――――――――――――――――――――――――――――――
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'


#――――――――――――――――――――――――――――――――
# configs
#――――――――――――――――――――――――――――――――
set -g default-terminal 'xterm-256color'
set -g automatic-rename on
set -g status-interval 1
set -g prefix C-f
set -g status-keys vi
set -g mode-keys vi
set -g base-index 1
set -g mouse on


#――――――――――――――――――――――――――――――――
# clipboard
#――――――――――――――――――――――――――――――――
set -g set-clipboard on
set -as terminal-features ',*:clipboard'
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
if-shell "uname | grep -q Darwin" {
  bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy';
  bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'pbcopy';
  bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy';
}


#――――――――――――――――――――――――――――――――
# styles
#――――――――――――――――――――――――――――――――
bground='#262626' # status bar color
active='#ffffff' # active text color
text='#808080'  # regular text color
warn='#ddaa00'  # warn text color
I="#{?client_prefix,,#I}#[fg=$active]#{?client_prefix,#I,}#[fg=$text]"
status_session="#[fg=$text][#{?client_prefix,,tmux:#S}"
status_pressed="#[fg=$active]#{?client_prefix,tmux->,}"
set -g pane-border-style fg="$text"
set -g pane-active-border-style fg="$active"
set -g mode-style "bg=$text,fg=$active"
set -g status-style "bg=$bground,fg=default"
set -g status-justify "left"
set -g status-left "$status_session$status_pressed#[fg=$text]] "
set -g status-right "#[fg=$text][%F|#[fg=$active]%T#[fg=$text]]"
set -g window-status-current-format "#[fg=$active]( #I:#W:#F )"
set -g window-status-format "#[fg=$text]($I:#W:#F)"
set -g message-style "bg=$bground,fg=$warn"


#――――――――――――――――――――――――――――――――
# hotkeys
#――――――――――――――――――――――――――――――――
bind a setw synchronize-panes
bind q set status
bind r source-file ~/.tmux.conf
bind v split-window -h
bind s split-window -v
bind P paste-buffer
bind f last-window


#――――――――――――――――――――――――――――――――
# exec
#――――――――――――――――――――――――――――――――
# tmux bug workaround (issue #295)
if-shell "uname | grep -q Darwin" \
  'set -g default-command "reattach-to-user-namespace $SHELL"' \
  'set -g default-command "$SHELL"'

# enable tmux-thumbs
set -g @thumbs-reverse enabled
if-shell "uname | grep -q Darwin" \
  "set -g @thumbs-command 'echo -n {} | pbcopy'" \
  "set -g @thumbs-command 'echo -n {} | wl-copy'"

# init tmux plugin manager - keep at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'

