---
name:
  .bash_history: "(#)"
  .bashrc: "(#)"
  .cache: "[?]"
  .cargo: "[#]"
  .config: "[#]"
  .env: "(#)"
  .env.example: "(#)"
  .git: "[#]"
  .gitconfig: "(#)"
  .github: "[#]"
  .gitignore: "(#)"
  .npm: "[#]"
  .profile: "(#)"
  .python_history: "(#)"
  .rustup: "[#]"
  .ssh: "[#]"
  .trash: "[?]"
  .vim: "[#]"
  .viminfo: "(#)"
  .vimrc: "(#)"
  .vscode: "[#]"
  .zsh_history: "(#)"
  .zshrc: "(#)"
  applications: "[$]"
  desktop: "[*]"
  documents: "[#]"
  docs: "[#]"
  dotfiles: "[#]"
  dots: "[#]"
  downloads: "[?]"
  music: "[>]"
  notes: "[#]"
  library: "[#]"
  pictures: "[>]"
  movies: "[>]"
  videos: "[>]"
  media: "[>]"
  public: "[+]"
  csh.cshrc: "{#}"
  csh.login: "{#}"
  csh.logout: "{#}"
  chs.logout: "{#}"
  cargo.toml: "{#}"
  compose.yaml: "{#}"
  compose.yml: "{#}"
  Dockerfile: "{$}"
  dockerfile: "{$}"
  group: "{#}"
  hosts: "{#}"
  LICENSE: "{#}"
  go.mod: "{#}"
  license: "{#}"
  pam.d: "[#]"
  profile: "{#}"
  README: "{#}"
  scripts: "[$]"
  shells: "{#}"
  makefile: "{$}"
  package.json: "{#}"
  pyproject.toml: "{#}"
  readme: "{#}"
  requirements.txt: "{#}"
  sudoers: "{#}"
  tsconfig.json: "{#}"
  venv: "[#]"
extension:
  7z: "{*}"
  bash: "{$}"
  bz2: "{*}"
  c: "{*}"
  cc: "{*}"
  cfg: "{#}"
  conf: "{#}"
  cpp: "{*}"
  cs: "{*}"
  css: "{*}"
  csv: "{#}"
  cxx: "{*}"
  db: "{#}"
  env: "{#}"
  fish: "{$}"
  flac: "{>}"
  gif: "{>}"
  go: "{*}"
  gz: "{*}"
  h: "{*}"
  hpp: "{*}"
  html: "{*}"
  ini: "{#}"
  ipynb: "{*}"
  jar: "{*}"
  java: "{*}"
  jpeg: "{>}"
  jpg: "{>}"
  js: "{*}"
  json: "{#}"
  jsx: "{*}"
  kt: "{*}"
  kts: "{*}"
  lock: "{#}"
  log: "{#}"
  lua: "{*}"
  m4a: "{>}"
  md: "{#}"
  mkv: "{>}"
  mov: "{>}"
  mp3: "{>}"
  mp4: "{>}"
  ods: "{#}"
  odt: "{#}"
  ogg: "{>}"
  pdf: "{#}"
  php: "{*}"
  png: "{>}"
  py: "{*}"
  pyi: "{*}"
  pyc: "{*}"
  rar: "{*}"
  rb: "{*}"
  rst: "{#}"
  rs: "{*}"
  sh: "{$}"
  sqlite: "{#}"
  sql: "{#}"
  svg: "{>}"
  tar: "{*}"
  toml: "{#}"
  ts: "{*}"
  tsv: "{#}"
  tsx: "{*}"
  txt: "{#}"
  wav: "{>}"
  webm: "{>}"
  webp: "{>}"
  xlsx: "{#}"
  xml: "{#}"
  xz: "{*}"
  yaml: "{#}"
  yml: "{#}"
  zip: "{*}"
  zsh: "{$}"
filetype:
  dir: "[*]"
  file: "{*}"
  pipe: "{~}"
  socket: "{~}"
  executable: "{$}"
  symlink-dir: "[@]"
  symlink-file: "{@}"
  device-char: "{~}"
  device-block: "{#}"
  special: "{?}"
